// Auto-generated by scripts/generate-og-routes.ts
// Run: bun run scripts/generate-og-routes.ts

import { OgImageExplorer } from "../components/elements/og-image-explorer";

const BASE_URL = "https://tryelements.dev";

const ROUTES = [
  // Pages (root-level)
  { path: "/", title: "Home", category: "pages" },
  { path: "/contributors", title: "Contributors", category: "pages" },
  { path: "/sponsor", title: "Sponsor", category: "pages" },
  // Providers
  { path: "/docs", title: "Documentation", category: "providers" },
  { path: "/docs/clerk", title: "Clerk", category: "providers" },
  { path: "/docs/devtools", title: "Dev Tools", category: "providers" },
  { path: "/docs/github", title: "GitHub", category: "providers" },
  { path: "/docs/logos", title: "Brand Logos", category: "providers" },
  { path: "/docs/polar", title: "Polar", category: "providers" },
  { path: "/docs/theme", title: "Theme", category: "providers" },
  { path: "/docs/tinte", title: "Tinte", category: "providers" },
  { path: "/docs/uploadthing", title: "UploadThing", category: "providers" },
  // Components - Dev Tools
  {
    path: "/docs/devtools/og-image-explorer",
    title: "OG Image Explorer",
    category: "devtools",
  },
  // Components - GitHub
  {
    path: "/docs/github/github-contributions",
    title: "GitHub Contributions",
    category: "github",
  },
  {
    path: "/docs/github/github-stars",
    title: "GitHub Stars",
    category: "github",
  },
  // Components - Polar
  {
    path: "/docs/polar/polar-sponsorship",
    title: "Polar Sponsorship",
    category: "polar",
  },
  // Components - Theme
  {
    path: "/docs/theme/theme-switcher-button",
    title: "Theme Switcher Button",
    category: "theme",
  },
  {
    path: "/docs/theme/theme-switcher-classic",
    title: "Theme Switcher Classic",
    category: "theme",
  },
  {
    path: "/docs/theme/theme-switcher-dropdown",
    title: "Theme Switcher Dropdown",
    category: "theme",
  },
  {
    path: "/docs/theme/theme-switcher-multi-button",
    title: "Theme Switcher Multi Button",
    category: "theme",
  },
  {
    path: "/docs/theme/theme-switcher-switch",
    title: "Theme Switcher Switch",
    category: "theme",
  },
  {
    path: "/docs/theme/theme-switcher-toggle",
    title: "Theme Switcher Toggle",
    category: "theme",
  },
  // Components - Tinte
  {
    path: "/docs/tinte/tinte-editor",
    title: "Tinte Theme Editor",
    category: "tinte",
  },
  // Components - UploadThing
  {
    path: "/docs/uploadthing/uploadthing-button",
    title: "UploadThing Button",
    category: "uploadthing",
  },
  {
    path: "/docs/uploadthing/uploadthing-dropzone",
    title: "UploadThing Dropzone",
    category: "uploadthing",
  },
].map((route) => ({
  ...route,
  ogImageUrl: `${BASE_URL}${route.path}/opengraph-image`,
}));

export default function OgImageExplorerPage() {
  return <OgImageExplorer routes={ROUTES} maxPerCategory={8} />;
}
