#!/usr/bin/env bun

/**
 * Build registry for distribution (Supabase pattern)
 *
 * This script:
 * 1. Imports registry from registry/index.ts
 * 2. Writes public/r/registry.json (without examples)
 * 3. Generates __registry__/index.tsx for ComponentPreview
 * 4. Runs `shadcn build` to create individual JSON files
 */

import { execSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const PUBLIC_REGISTRY_DIR = join(process.cwd(), "public/r");
const REGISTRY_INDEX_DIR = join(process.cwd(), "__registry__");

function ensureDir(path: string) {
  if (!existsSync(path)) {
    mkdirSync(path, { recursive: true });
  }
}

async function main() {
  console.log("🚀 Building Elements registry (Supabase pattern)...\n");

  // Step 0: Build SFX assets (generate TS modules from MP3s before registry scan)
  console.log("🔊 Step 0: Building SFX assets...");
  try {
    execSync("bun run scripts/build-sfx.ts", { stdio: "inherit" });
  } catch (_error) {
    console.error("\n❌ SFX build failed");
    process.exit(1);
  }

  // Step 0.5: Regenerate registry/index.ts to pick up SFX items
  console.log("\n📋 Step 0.5: Regenerating registry index...");
  try {
    execSync("bun run scripts/generate-registry-index.ts", {
      stdio: "inherit",
    });
  } catch (_error) {
    console.error("\n❌ Registry index generation failed");
    process.exit(1);
  }

  // Step 1: Import registry
  console.log("\n📝 Step 1: Importing registry...");

  // Dynamic import to get the registry
  const registryModule = await import("../registry/index");
  const registry = registryModule.registry;

  console.log(`   ✓ Loaded ${registry.items.length} total items`);

  // Step 2: Prepare public registry (filter out examples)
  console.log("\n📦 Step 2: Preparing public registry.json...");

  const cleanedRegistry = {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    ...registry,
    items: registry.items.filter(
      (item: any) => item.type !== "registry:example",
    ),
  };

  // Ensure directories exist
  ensureDir(PUBLIC_REGISTRY_DIR);
  ensureDir(REGISTRY_INDEX_DIR);

  // Write registry.json
  const registryPath = join(PUBLIC_REGISTRY_DIR, "registry.json");
  writeFileSync(registryPath, JSON.stringify(cleanedRegistry, null, 2));
  console.log(`   ✓ Wrote ${registryPath}`);
  console.log(`   ✓ ${cleanedRegistry.items.length} public components`);

  // Step 3: Generate __registry__/index.tsx for ComponentPreview
  console.log("\n🎨 Step 3: Generating __registry__/index.tsx...");

  const exampleComponents = registry.items.filter(
    (item: any) => item.type === "registry:example",
  );

  const registryIndexContent = `
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index = {
  "default": {
    ${exampleComponents
      .map((item: any) => {
        const componentFile = item.files?.find((file: any) =>
          file.path.endsWith(".tsx"),
        );
        if (!componentFile) return null;

        return `
    "${item.name}": {
      component: React.lazy(() => import("@/${componentFile.path}")),
    }`;
      })
      .filter(Boolean)
      .join(",\n")}
  },
} as const
`;

  const registryIndexPath = join(REGISTRY_INDEX_DIR, "index.tsx");
  writeFileSync(registryIndexPath, registryIndexContent);
  console.log(`   ✓ Wrote ${registryIndexPath}`);
  console.log(`   ✓ ${exampleComponents.length} example components registered`);

  // Step 4: Run shadcn build to generate individual component JSON files with inline content
  console.log("\n🔨 Step 4: Running shadcn build...");
  try {
    execSync("bunx shadcn@latest build public/r/registry.json", {
      stdio: "inherit",
    });
  } catch (_error) {
    console.error("\n❌ shadcn build failed");
    process.exit(1);
  }

  // Step 5: Generate logos-index.json for @tryelements/cli
  console.log("\n📋 Step 5: Generating logos-index.json...");
  const logoNames = registry.items
    .filter((item: any) => item.name.endsWith("-logo"))
    .map((item: any) => item.name.replace(/-logo$/, ""));
  const logosIndexPath = join(PUBLIC_REGISTRY_DIR, "logos-index.json");
  writeFileSync(logosIndexPath, JSON.stringify(logoNames, null, 2));
  console.log(`   ✓ Wrote ${logosIndexPath} (${logoNames.length} logos)`);

  // Step 6: Generate raw SVG files for @tryelements CLI
  console.log("\n🖼️  Step 6: Generating raw SVG files...");
  try {
    const { generateSvgFiles } = await import("./generate-svg-files");
    const svgResult = generateSvgFiles();
    console.log(
      `   ✓ ${svgResult.success} SVGs generated${svgResult.failed > 0 ? ` (${svgResult.failed} failed)` : ""}`,
    );
  } catch (_error) {
    console.error("\n❌ SVG generation failed:", _error);
  }

  // Step 7: Generate hooks-index.json and copy hook scripts
  console.log("\n🪝 Step 7: Generating hooks-index.json...");
  try {
    const hooksDir = join(process.cwd(), "registry/default/blocks/hooks");
    const publicHooksDir = join(process.cwd(), "public/hooks");
    ensureDir(publicHooksDir);

    const hookDirs = readdirSync(hooksDir, { withFileTypes: true })
      .filter((d) => d.isDirectory() && !d.name.startsWith("_"))
      .map((d) => d.name);

    const BUNDLES: Record<string, string[]> = {
      starter: ["notify-macos", "guard-branch", "auto-format"],
      safety: ["guard-branch", "guard-secrets", "guard-destructive"],
      notifications: [
        "notify-macos",
        "notify-sound",
        "notify-slack",
        "notify-discord",
        "notify-telegram",
      ],
    };

    const hooks = hookDirs.map((name) => {
      const hookDir = join(hooksDir, name);
      const hookMeta = JSON.parse(
        readFileSync(join(hookDir, "hook.json"), "utf-8"),
      );
      const registryItem = JSON.parse(
        readFileSync(join(hookDir, "registry-item.json"), "utf-8"),
      );

      const scriptsDir = join(hookDir, "scripts");
      if (existsSync(scriptsDir)) {
        const scriptFiles = readdirSync(scriptsDir).filter((f) =>
          f.endsWith(".sh"),
        );
        for (const scriptFile of scriptFiles) {
          copyFileSync(
            join(scriptsDir, scriptFile),
            join(publicHooksDir, scriptFile),
          );
        }
      }

      return {
        name,
        event: hookMeta.event,
        type: hookMeta.type,
        matcher: hookMeta.matcher ?? null,
        platforms: hookMeta.platforms ?? [],
        tags: hookMeta.tags ?? [],
        title: registryItem.title,
        description: registryItem.description,
        configurable: hookMeta.configurable ?? {},
        registry: `https://tryelements.dev/r/${registryItem.name}.json`,
        script: `https://tryelements.dev/hooks/${name}.sh`,
      };
    });

    const hooksIndex = {
      generated: new Date().toISOString(),
      count: hooks.length,
      hooks,
      bundles: BUNDLES,
    };

    const hooksIndexPath = join(PUBLIC_REGISTRY_DIR, "hooks-index.json");
    writeFileSync(hooksIndexPath, JSON.stringify(hooksIndex, null, 2));
    console.log(`   ✓ Wrote ${hooksIndexPath} (${hooks.length} hooks)`);
    console.log(
      `   ✓ Copied ${hooks.length} hook scripts to ${publicHooksDir}`,
    );
  } catch (_error) {
    console.error("\n❌ Hooks index generation failed:", _error);
  }

  console.log("\n✨ Registry build complete!");
  console.log(`   📁 Public registry: ${PUBLIC_REGISTRY_DIR}`);
  console.log(`   📁 Preview registry: ${REGISTRY_INDEX_DIR}`);
  console.log("\n   You can now:");
  console.log(
    "   1. Test locally: npx shadcn add http://localhost:3000/r/clerk-sign-in-shadcn.json",
  );
  console.log("   2. Use ComponentPreview in docs to show examples");
  console.log("   3. Deploy to production and share your registry!");
}

main();
