#!/usr/bin/env bun
/**
 * Generate OG Image routes for the OG Image Explorer
 * Scans the app directory and content files to build a complete routes list
 *
 * Usage:
 *   bun run scripts/generate-og-routes.ts
 *   bun run scripts/generate-og-routes.ts --base-url https://your-site.com
 */

import { Glob } from "bun";
import { readFileSync } from "fs";
import { basename, dirname } from "path";

interface OgRoute {
  path: string;
  title: string;
  category: string;
}

const args = process.argv.slice(2);
const baseUrlIndex = args.indexOf("--base-url");
const BASE_URL =
  baseUrlIndex !== -1 ? args[baseUrlIndex + 1] : "https://tryelements.dev";

function extractTitleFromMdx(filePath: string): string | null {
  try {
    const content = readFileSync(filePath, "utf-8");
    const titleMatch = content.match(/^title:\s*["']?([^"'\n]+)["']?/m);
    return titleMatch ? titleMatch[1].trim() : null;
  } catch {
    return null;
  }
}

function slugToTitle(slug: string): string {
  return slug
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

const routes: OgRoute[] = [];

// 1. Root pages (manually defined - these are static)
const rootPages: OgRoute[] = [
  { path: "/", title: "Home", category: "pages" },
  { path: "/contributors", title: "Contributors", category: "pages" },
  { path: "/sponsor", title: "Sponsor", category: "pages" },
];
routes.push(...rootPages);

// 2. Docs index
routes.push({ path: "/docs", title: "Documentation", category: "providers" });
routes.push({
  path: "/docs/logos",
  title: "Brand Logos",
  category: "providers",
});

// 3. Provider pages from content/providers/*.mdx
const providerGlob = new Glob("src/content/providers/*.mdx");
for await (const file of providerGlob.scan(".")) {
  const slug = basename(file, ".mdx");
  const title = extractTitleFromMdx(file) || slugToTitle(slug);
  routes.push({ path: `/docs/${slug}`, title, category: "providers" });
}

// 4. Component pages from content/components/**/*.mdx
const componentGlob = new Glob("src/content/components/**/*.mdx");
for await (const file of componentGlob.scan(".")) {
  const componentSlug = basename(file, ".mdx");
  const providerSlug = basename(dirname(file));
  const title = extractTitleFromMdx(file) || slugToTitle(componentSlug);
  routes.push({
    path: `/docs/${providerSlug}/${componentSlug}`,
    title,
    category: providerSlug,
  });
}

// Sort routes: root first, then docs, then by path
routes.sort((a, b) => {
  if (a.path === "/") return -1;
  if (b.path === "/") return 1;
  if (a.path.startsWith("/docs") && !b.path.startsWith("/docs")) return 1;
  if (!a.path.startsWith("/docs") && b.path.startsWith("/docs")) return -1;
  return a.path.localeCompare(b.path);
});

// Output
console.log(`// Auto-generated by scripts/generate-og-routes.ts`);
console.log(`// Run: bun run scripts/generate-og-routes.ts\n`);
console.log(`const BASE_URL = "${BASE_URL}";\n`);
console.log(`const ROUTES = [`);

for (const route of routes) {
  console.log(
    `  { path: "${route.path}", title: "${route.title}", category: "${route.category}" },`,
  );
}

console.log(`].map((route) => ({`);
console.log(`  ...route,`);
console.log(`  ogImageUrl: \`\${BASE_URL}\${route.path}/opengraph-image\`,`);
console.log(`}));\n`);

console.log(`// Total: ${routes.length} routes`);
