#!/usr/bin/env bun

/**
 * Automatically generates component preview mappings from registry files.
 * This script reads all registry.json files and creates static imports
 * that Next.js can analyze at build time.
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface RegistryFile {
  path: string;
  type: string;
}

interface RegistryItem {
  name: string;
  type: string;
  files?: RegistryFile[];
}

interface Registry {
  items: RegistryItem[];
}

const REGISTRY_DIR = join(process.cwd(), "src/registry");
const OUTPUT_FILE = join(
  process.cwd(),
  "src/lib/component-preview-map.generated.tsx",
);

console.log("🔍 Scanning registries for previewable components...\n");

const imports: string[] = [];
const mappings: string[] = [];
const providers = readdirSync(REGISTRY_DIR);

for (const provider of providers) {
  const registryPath = join(REGISTRY_DIR, provider, "registry.json");

  if (!existsSync(registryPath)) {
    console.log(`⚠️  No registry found for ${provider}`);
    continue;
  }

  const registry: Registry = JSON.parse(readFileSync(registryPath, "utf-8"));

  console.log(`📦 Processing ${provider}:`);

  for (const item of registry.items) {
    // Determine if component is previewable based on conventions
    const isPreviewable =
      item.type === "registry:ui" ||
      (item.type === "registry:block" &&
        item.files?.some((f) => f.type === "registry:component"));

    if (!isPreviewable) {
      console.log(`   ⏭️  Skipping ${item.name} (type: ${item.type})`);
      continue;
    }

    // Find the component file to load
    // Only use component type - page/layout files have app-specific imports
    const componentFile = item.files?.find(
      (f) => f.type === "registry:component",
    );

    if (!componentFile) {
      console.log(`   ⚠️  No component file for ${item.name}`);
      continue;
    }

    // Extract module path from registry path
    // e.g., "registry/clerk/sign-in-shadcn/sign-in.tsx" -> "clerk/sign-in-shadcn/sign-in"
    const pathParts = componentFile.path.split("/");
    const registryIndex = pathParts.indexOf("registry");

    if (registryIndex === -1) {
      console.log(`   ⚠️  Invalid path format for ${item.name}`);
      continue;
    }

    const modulePath = pathParts
      .slice(registryIndex + 1)
      .join("/")
      .replace(/\.(tsx?|jsx?)$/, "");

    // Generate unique import name
    const importName = item.name
      .split("-")
      .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
      .join("");

    // Add import statement using @/registry path alias
    imports.push(
      `import * as ${importName}Module from "@/registry/${modulePath}";`,
    );

    // Add to mapping
    mappings.push(`  "${item.name}": ${importName}Module,`);

    console.log(`   ✅ ${item.name} -> @/registry/${modulePath}`);
  }

  console.log();
}

// Generate the file content
const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by scripts/generate-preview-map.ts
 * Run: bun run scripts/generate-preview-map.ts
 *
 * Convention-based component preview mappings:
 * - registry:ui components are previewable
 * - registry:block components with registry:component files are previewable
 * - Other types (lib, hook, etc.) are not previewable
 */

import type { ComponentType } from "react";

${imports.join("\n")}

interface ComponentModule {
  default?: ComponentType<any>;
  [key: string]: any;
}

export const componentPreviewMap: Record<string, ComponentModule> = {
${mappings.join("\n")}
};

/**
 * Get a component from the preview map.
 * Extracts the default export or first named component export.
 */
export function getPreviewComponent(name: string): ComponentType<any> | null {
  const module = componentPreviewMap[name];

  if (!module) {
    return null;
  }

  // Try default export first
  if (module.default) {
    return module.default;
  }

  // Find first function export (component)
  for (const [key, value] of Object.entries(module)) {
    if (typeof value === "function" && key !== "default") {
      return value as ComponentType<any>;
    }
  }

  return null;
}
`;

// Write the generated file
writeFileSync(OUTPUT_FILE, fileContent, "utf-8");

console.log(`✨ Generated preview map: ${OUTPUT_FILE}`);
console.log(`📊 Total previewable components: ${mappings.length}`);
