// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

export const Index = {
  default: {
    "clerk-sign-in-shadcn-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/clerk-sign-in-shadcn-demo.tsx"),
      ),
    },

    "clerk-sign-up-shadcn-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/clerk-sign-up-shadcn-demo.tsx"),
      ),
    },

    "clerk-sign-in-signals-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/clerk-sign-in-signals-demo.tsx"),
      ),
    },

    "clerk-sign-up-signals-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/clerk-sign-up-signals-demo.tsx"),
      ),
    },

    "clerk-waitlist-shadcn-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/clerk-waitlist-shadcn-demo.tsx"),
      ),
    },

    "theme-switcher-demo": {
      component: React.lazy(
        () => import("@/registry/default/examples/theme-switcher-demo.tsx"),
      ),
    },

    "theme-switcher-button-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/theme-switcher-button-demo.tsx"),
      ),
    },

    "theme-switcher-dropdown-demo": {
      component: React.lazy(
        () =>
          import(
            "@/registry/default/examples/theme-switcher-dropdown-demo.tsx"
          ),
      ),
    },

    "theme-switcher-multi-button-demo": {
      component: React.lazy(
        () =>
          import(
            "@/registry/default/examples/theme-switcher-multi-button-demo.tsx"
          ),
      ),
    },

    "theme-switcher-switch-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/theme-switcher-switch-demo.tsx"),
      ),
    },

    "theme-switcher-toggle-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/theme-switcher-toggle-demo.tsx"),
      ),
    },

    "tinte-editor-demo": {
      component: React.lazy(
        () => import("@/registry/default/examples/tinte-editor-demo.tsx"),
      ),
    },

    "polar-sponsorship-demo": {
      component: React.lazy(
        () => import("@/registry/default/examples/polar-sponsorship-demo.tsx"),
      ),
    },

    "uploadthing-button-demo": {
      component: React.lazy(
        () => import("@/registry/default/examples/uploadthing-button-demo.tsx"),
      ),
    },

    "uploadthing-dropzone-demo": {
      component: React.lazy(
        () =>
          import("@/registry/default/examples/uploadthing-dropzone-demo.tsx"),
      ),
    },
  },
} as const;
